apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rhoas-kafka-helm.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name:  {{ include "rhoas-kafka-helm.fullname" . }}
  template:
    spec:
      containers:
        - env:
            - name: BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.rhoas.config }}
                  key: kafka-bootstrap-server-hosts
            - name: OAUTH_TOKEN_ENDPOINT_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.rhoas.config }}
                  key: oauth-token-url
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name:  {{ .Values.rhoas.secret }}
                  key: client-id
            - name: CLIENT_CLIENT_SECRET  
              valueFrom:
                secretKeyRef:
                  name:  {{ .Values.rhoas.secret }}
                  key: client-secret
          image: wtrocki/rhoas-quarkus-kafka-quickstart:1.0-SNAPSHOT
          imagePullPolicy: Always
          name: rhoas-quarkus-kafka-quickstart
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
