apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 30bd61d434292e7c104811aaa531b1ebc233ac6e
    app.quarkus.io/build-timestamp: 2021-11-10 - 16:26:10 +0000
  labels:
    app.kubernetes.io/name: rhoas-quarkus-kafka-quickstart
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: rhoas-quarkus-kafka-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rhoas-quarkus-kafka-quickstart
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 30bd61d434292e7c104811aaa531b1ebc233ac6e
        app.quarkus.io/build-timestamp: 2021-11-10 - 16:26:10 +0000
      labels:
        app.kubernetes.io/name: rhoas-quarkus-kafka-quickstart
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: wtrocki/rhoas-quarkus-kafka-quickstart:1.0-SNAPSHOT
          imagePullPolicy: Always
          name: rhoas-quarkus-kafka-quickstart
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
