apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 30bd61d434292e7c104811aaa531b1ebc233ac6e
    app.quarkus.io/build-timestamp: 2021-11-10 - 16:26:10 +0000
  labels:
    app.kubernetes.io/name: rhoas-quarkus-kafka-quickstart
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: rhoas-quarkus-kafka-quickstart
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: rhoas-quarkus-kafka-quickstart
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP